### ISSUE TITLE
Podcast unavailable on Castro app

### ISSUE THREAD

**Issue by ajitid** [isaacrlevin/CoffeeAndOpenSource.com#5]
Hi Isaac! I listen to podcasts on https://castro.fm/ but couldn't find it there. Any idea why?

**Comment by isaacrlevin** [comment]
Have you tried the RSS feed?
https://anchor.fm/s/63982f70/podcast/rss

**Comment by ajitid** [comment]
I found a way: https://castro.fm/support/link-to-your-podcast-in-castro. I used this to generate a Castro link. This resulted in https://castro.fm/podcast/014e4654-a652-4e66-ac75-cccc84c30f13. 
Seems like Castro supports OPML but not a way to externally add an RSS feed. 🤦‍♂️
